"""
Django settings for ac_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from decouple import config
# import Celery’s cron-style scheduler helper
from celery.schedules import crontab
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 
SECRET_KEY = config("SECRET_KEY", default="unsafe-default-key")

# 
DEBUG = config("DEBUG", default=False, cast=bool)


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts_core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Attach .company to request based on logged-in user
    "accounts_core.middleware.CurrentCompanyMiddleware",
]

ROOT_URLCONF = "ac_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ac_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
   "default": {  # Read sensitive info from environment variables
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB", default="mydb"),
        "USER": config("POSTGRES_USER", default="myuser"),
        "PASSWORD": config("POSTGRES_PASSWORD", default="password"),
        "HOST": config("POSTGRES_HOST", default="localhost"),
        "PORT": config("POSTGRES_PORT", default="5432"),
    }
    # Locally: .env provides credentials.
    # On CI / production: set real environment variables (export POSTGRES_PASSWORD=supersecret)
    # No sensitive data is ever committed to GitHub.
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

UASValidator = [
    "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": UASValidator[0],
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts_core.User"

# Schedule background full recomputation with Celery beat


""" Run accounts_core.tasks.recompute_all_snapshots function now. """
CELERY_BEAT_SCHEDULE = {  # tell Celery Beat what to run and when
    "recompute-snapshots-nightly": {  # label for your job
        # import path to task function
        "task": "accounts_core.tasks.recompute_all_snapshots",
        "schedule": crontab(hour=0, minute=0),  # run once a day at midnight
        "args": (1,),  # pass arguments to the task (company_id=1)
    },
}

# Tell Celery where to send & receive jobs
CELERY_BROKER_URL = (
    # Celery needs message broker (redis) to queue tasks
    "redis://localhost:6379/0"
)
""" Use Redis server running on localhost/same machine.
Port 6379 is Redis default.
Database 0 - Redis lets you have multiple logical DBs, numbered 0-15. """
