# Generated by Django 5.2.5 on 2025-09-06 15:56

from decimal import Decimal

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "account_number_masked",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("currency_code", models.CharField(default="USD", max_length=10)),
                ("last_reconciled_at", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(blank=True, max_length=8, null=True)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                "verbose_name_plural": "currencies",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                (
                    "ac_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        default="debit",
                        max_length=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts_core.accountcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="accounts_core.currency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(blank=True, max_length=64, null=True)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts_core.company"
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts_core.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accountcategory",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts_core.company"
            ),
        ),
        migrations.CreateModel(
            name="AccountBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "debit_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "credit_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts_core.company"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_users",
                to="accounts_core.company",
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("payment_terms_days", models.IntegerField(default=30)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "default_ar_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers_default_ar",
                        to="accounts_core.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("accountant", "Accountant"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts_core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_code", models.CharField(blank=True, max_length=80, null=True)),
                ("description", models.CharField(max_length=400)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("useful_life_years", models.IntegerField(blank=True, null=True)),
                (
                    "depreciation_method",
                    models.CharField(
                        default='straight_line How depreciation is calculated:\n                                    "straight_line" = equal expense every year.\n                                    Other methods could include "declining_balance", "units_of_production". ',
                        max_length=30,
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankTransactionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applied_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.banktransaction",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=80, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "on_hand_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0"), max_digits=14
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "purchase_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_purchase_account",
                        to="accounts_core.account",
                    ),
                ),
                (
                    "sales_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_sales_account",
                        to="accounts_core.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=14
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales / revenue account for this line",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=14
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense/purchase account for this line",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.account",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.bill",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft Once posted, becomes immutable. ",
                        max_length=10,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("source_type", models.CharField(blank=True, max_length=50, null=True)),
                ("source_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("is_posted", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.account",
                    ),
                ),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.banktransaction",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts_core.bill",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "fixed_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.fixedasset",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts_core.invoice",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.journalentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts_core.company",
                    ),
                ),
            ],
            options={
                "ordering": ("company", "start_date"),
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts_core.period",
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("payment_terms_days", models.IntegerField(default=30)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
                (
                    "default_ap_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendors_default_ap",
                        to="accounts_core.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts_core.vendor",
            ),
        ),
        migrations.CreateModel(
            name="BankTransactionBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applied_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.banktransaction",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.bill",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts_core.company",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bank_transaction", "bill"), name="unique_bank_tx_bill"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("applied_amount__gte", 0)),
                        name="bt_bill_non_negative_amounts",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["company", "bank_account"],
                name="accounts_co_company_ce82b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["company", "payment_date"],
                name="accounts_co_company_18379a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["company", "name"], name="accounts_co_company_d27342_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uq_company_bankaccount_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountcategory",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uq_company_accountcategory_name"
            ),
        ),
        migrations.AddIndex(
            model_name="accountbalancesnapshot",
            index=models.Index(
                fields=["company", "snapshot_date"],
                name="accounts_co_company_b1fd3d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountbalancesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("debit_balance__gte", 0), ("credit_balance__gte", 0)
                ),
                name="ab_snap_non_negative_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountbalancesnapshot",
            constraint=models.UniqueConstraint(
                fields=("company", "account", "snapshot_date"),
                name="uq_company_account_snapshot_date",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["company", "ac_type"], name="accounts_co_company_0a8331_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["company", "code"], name="accounts_co_company_2fc5f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["company", "parent"], name="accounts_co_company_32b747_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="uq_company_account_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uq_company_customer_name"
            ),
        ),
        migrations.AddIndex(
            model_name="entitymembership",
            index=models.Index(
                fields=["company", "user"], name="accounts_co_company_a8230d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymembership",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="uq_user_company_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["company", "asset_code"], name="accounts_co_company_4bbc2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "invoice_number"],
                name="accounts_co_company_8bac49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "customer"], name="accounts_co_company_9884e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("company", "invoice_number"), name="uq_invoice_company_number"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransactioninvoice",
            index=models.Index(
                fields=["company", "bank_transaction"],
                name="accounts_co_company_bc4a13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransactioninvoice",
            index=models.Index(
                fields=["company", "invoice"], name="accounts_co_company_d6d7d2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransactioninvoice",
            constraint=models.UniqueConstraint(
                fields=("bank_transaction", "invoice"), name="unique_bank_tx_invoice"
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransactioninvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("applied_amount__gte", 0)),
                name="bt_inv_non_negative_amounts",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["company", "name"], name="accounts_co_company_22b71a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("company", "sku"), name="uq_company_item_sku"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["company", "invoice"], name="accounts_co_company_94bf0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["company", "account"], name="accounts_co_company_a04827_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0), ("unit_price__gte", 0)),
                name="invl_non_negative_amounts",
            ),
        ),
        migrations.AddIndex(
            model_name="billline",
            index=models.Index(
                fields=["company", "bill"], name="accounts_co_company_208237_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0), ("unit_price__gte", 0)),
                name="bl_non_negative_amounts",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["company", "account"], name="accounts_co_company_28d89c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["company", "journal"], name="accounts_co_company_5572b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit_amount__gte", 0), ("credit_amount__gte", 0)),
                name="jl_non_negative_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uq_company_period_name"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company", "date"], name="accounts_co_company_650b75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company", "status"], name="accounts_co_company_55b62c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uq_company_vendor_name"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["company", "bill_number"], name="accounts_co_company_e964dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["company", "vendor"], name="accounts_co_company_61dded_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                fields=("company", "bill_number"), name="uq_bill_company_number"
            ),
        ),
    ]
