# Generated by Django 5.2.5 on 2025-09-06 16:16

import accounts_core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='accountbalancesnapshot',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='accountcategory',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='auditlog',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bankaccount',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='banktransaction',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='banktransactionbill',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='banktransactioninvoice',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bill',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='billline',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='entitymembership',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fixedasset',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoiceline',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='journalentry',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='journalline',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='period',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='vendor',
            managers=[
                ('objects', accounts_core.managers.TenantManager()),
            ],
        ),
    ]
