# Generated by Django 5.2.5 on 2025-09-08 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0002_alter_account_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounts_core.invoice",
            ),
        ),
    ]
