# Generated by Django 5.2.5 on 2025-09-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0003_alter_invoiceline_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('unapplied', 'Unapplied'), ('partially_applied', 'Partially applied'), ('fully_applied', 'Fully applied')], default='unapplied', max_length=20),
        ),
    ]
