# Generated by Django 5.2.5 on 2025-09-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0004_banktransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_control_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='account',
            field=models.ForeignKey(blank=True, help_text='GL account where this asset is capitalized', limit_choices_to={'ac_type': 'Asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_core.account'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('capitalized', 'Capitalized'), ('disposed', 'Disposed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor from whom this asset was purchased', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_core.vendor'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_ar_account',
            field=models.ForeignKey(blank=True, help_text='Default AR account used for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_default_ar', to='accounts_core.account'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_ap_account',
            field=models.ForeignKey(blank=True, help_text='Default AP account used for this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_default_ap', to='accounts_core.account'),
        ),
    ]
