# Generated by Django 5.2.5 on 2025-09-18 15:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0016_balancesheetrunning_journallineaggperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18),
        ),
    ]
