# Generated by Django 5.2.5 on 2025-09-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0017_item_default_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts_core.bill'),
        ),
    ]
