# Generated by Django 5.2.5 on 2025-09-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0020_backfill_journalline_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSheetRunning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("account_id", models.IntegerField()),
                ("account_code", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=50)),
                (
                    "balance_to_date_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "balance_to_date_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Balance Sheet Running",
                "verbose_name_plural": "Balance Sheet Running Records",
                "db_table": "mv_balance_sheet_running",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JournalLineAggPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("period_id", models.IntegerField()),
                ("last_txn_date", models.DateField()),
                ("account_id", models.IntegerField()),
                ("account_code", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=50)),
                (
                    "total_debit_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_credit_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "net_amount_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_debit_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_credit_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "net_amount_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Journal Line Period Aggregate",
                "verbose_name_plural": "Journal Line Period Aggregate Records",
                "db_table": "mv_jl_agg_period",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProfitLossPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("period_id", models.IntegerField()),
                (
                    "total_income_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_expense_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "net_profit_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_income_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_expense_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "net_profit_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Profit & Loss Period",
                "verbose_name_plural": "Profit & Loss Period Records",
                "db_table": "mv_pl_period",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TrialBalancePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("period_id", models.IntegerField()),
                ("account_id", models.IntegerField()),
                ("account_code", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=50)),
                (
                    "period_debit_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "period_credit_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "period_balance_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "period_debit_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "period_credit_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "period_balance_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Trial Balance Period",
                "verbose_name_plural": "Trial Balance Period Records",
                "db_table": "mv_trial_balance_period",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TrialBalanceRunning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("account_id", models.IntegerField()),
                ("account_code", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=50)),
                (
                    "total_debit_to_date_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_credit_to_date_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "balance_to_date_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_debit_to_date_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "total_credit_to_date_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "balance_to_date_local",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Trial Balance Running",
                "verbose_name_plural": "Trial Balance Running Records",
                "db_table": "mv_trial_balance_running",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("ready", "Ready"), ("posted", "Posted")],
                default='draft JournalEntry workflow:\n ("Draft") # still editable\n                            ("Ready") # validated but not yet posted\n                            ("Posted") # finalized\n                        ',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="currency",
            field=models.ForeignKey(
                default="USD",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts_core.currency",
            ),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounts_core.journalentry",
            ),
        ),
    ]
