# Generated by Django 5.2.5 on 2025-12-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0020_alter_fixedasset_depreciation_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="ledger_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Ledger account that represents this bank account in the chart of accounts",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts_core.account",
            ),
        ),
    ]
