# Generated by Django 5.2.5 on 2025-12-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0021_bankaccount_ledger_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransactioninvoice",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="JournalEntry created when this payment was applied to the invoice.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction_invoices",
                to="accounts_core.journalentry",
            ),
        ),
    ]
