# Generated by Django 5.2.5 on 2025-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0022_banktransactioninvoice_journal_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("partially_paid", "Partially paid"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=14,
            ),
        ),
    ]
