# Generated by Django 5.2.5 on 2025-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0023_banktransaction_description_alter_billline_bill"),
    ]

    operations = [ ]
