# Generated by Django 5.2.5 on 2025-12-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0024_invoice_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedasset",
            name="depreciation_method",
            field=models.CharField(
                default='straight_line How depreciation is calculated:\n            "straight_line" = equal expense every year.\n             Other methods could include\n             "declining_balance", "units_of_production". ',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("ready", "Ready"), ("posted", "Posted")],
                default='draft JournalEntry workflow:\n                            ("Draft") # still editable\n                            ("Ready") # validated but not yet posted\n                            ("Posted") # finalized\n                        ',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="fx_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
    ]
