# Generated by Django 5.2.5 on 2025-12-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0025_alter_fixedasset_depreciation_method_and_more"),
    ]

    operations = [
    ]
