# Generated by Django 5.2.5 on 2025-12-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0026_bankaccount_ledger_account"),
    ]

    operations = [
    ]
