# Generated by Django 5.2.5 on 2025-12-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0028_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedasset",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="GL account where this asset is capitalized",
                limit_choices_to={"ac_type": "asset"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts_core.account",
            ),
        ),
    ]
