# Generated by Django 5.2.5 on 2025-12-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0029_alter_fixedasset_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedasset",
            name="depreciation_method",
            field=models.CharField(
                default="straight_line",
                help_text="How depreciation is calculated: straight_line = equal expense every year. Other methods could include declining_balance & units_of_production",
                max_length=30,
            ),
        ),
    ]
