# Generated by Django 5.2.5 on 2025-12-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0014_mv_balance_sheet_running"),
        ("accounts_core", "0030_alter_fixedasset_depreciation_method"),
    ]

    operations = []
