# Generated by Django 5.2.5 on 2025-12-22 13:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0031_merge_20251222_1343"),
    ]

    operations = [
        
    ]
