# Generated by Django 5.2.5 on 2025-12-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_core", "0032_bankaccount_ledger_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="ledger_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Ledger account that represents this bank account in the chart of accounts",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts_core.account",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banktransactioninvoice",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="JournalEntry created when this payment was applied to the invoice.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction_invoices",
                to="accounts_core.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posting_fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
